### ISSUE TITLE
Workspace.get is deprecated.

### ISSUE THREAD

**Issue by Naggertooth** [atom/archive-view#53]
`atom.workspace.paneContainer` has always been private, but it is now gone. Please use `atom.workspace.getCenter()` instead and consult the workspace API docs for public methods.
```
Workspace.get (<embedded>:24639:18)
Object.activate (C:\Users\user\.atom\packages\atom-ftp-editor\lib\main.js:52:21)
Package.activateNow (<embedded>:68361:25)
<unknown> (<embedded>:69076:31)
Function.module.exports.Emitter.simpleDispatch (<embedded>:62396:20)
Emitter.emit (<embedded>:62512:34)
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-ftp-editor](https://atom.io/packages/atom-ftp-editor) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
