### ISSUE TITLE
path.extname is deprecated.

### ISSUE THREAD

**Issue by fsgjiajia** [atom/archive-view#61]
Argument to `path.extname` must be a string
```
path.extname (F:\Atom\resources\app.asar\src\electron-shims.js:20:10)
ATPOutputView.getCwd (C:\Users\Administrator.USER-20180216FG\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:1874:17)
BuiltinVariables.parseFull (C:\Users\Administrator.USER-20180216FG\.atom\packages\atom-terminal-panel\lib\atp-builtins-variables.coffee:188:77)
BuiltinVariables.parseHtml (C:\Users\Administrator.USER-20180216FG\.atom\packages\atom-terminal-panel\lib\atp-builtins-variables.coffee:111:16)
ATPOutputView.parseTemplate (C:\Users\Administrator.USER-20180216FG\.atom\packages\atom-terminal-panel\lib\atp-view.coffee:664:36)
ATPPanel.updateStatusBar (C:\Users\Administrator.USER-20180216FG\.atom\packages\atom-terminal-panel\lib\atp-panel.coffee:190:50)
```

**Comment by thomasjo** [comment]
Thanks for contributing!

It appears that this is being caused by the [atom-terminal-panel](https://atom.io/packages/atom-terminal-panel) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
