### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by AnetteMM** [atom/archive-view#69]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (D:\abc_my folders\cherrytrees\Atom\Atom\resources\app.asar\src\text-editor-element.js:13:10)
MarkdownScrlSync.getVisTopHgtBot (C:\Users\PC\.atom\packages\markdown-scroll-sync\lib\utils.coffee:20:34)
MarkdownScrlSync.setMap (C:\Users\PC\.atom\packages\markdown-scroll-sync\lib\map.coffee:25:14)
MarkdownScrlSync.startTracking (C:\Users\PC\.atom\packages\markdown-scroll-sync\lib\main.coffee:75:12)
<unknown> (C:\Users\PC\.atom\packages\markdown-scroll-sync\lib\main.coffee:58:23)
Function.simpleDispatch (<embedded>:11:1190583)
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [markdown-scroll-sync](https://atom.io/packages/markdown-scroll-sync) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
